language: node_js
node_js:
- 8
dist: trusty
cache:
  directories:
  - node_modules
  - client/node_modules
# Encrypt googleKey file and allow usb connection
before_install:
- openssl aes-256-cbc -K $encrypted_98a29f15986b_key -iv $encrypted_98a29f15986b_iv
  -in googleKey.json.enc -out googleKey.json -d
- sudo apt-get update
- sudo apt-get install build-essential git -y
- sudo apt-get install libudev-dev -y
- sudo apt-get install libusb-1.0-0-dev -y
- sudo apt-get install gcc-4.8 g++-4.8 -y
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- npm install
- cd client && npm install
script:
- npm run CI=true react-scripts test --env=jsdom
- cd .. && npm run lint
- npm run test
